cecho("\n<white>- <gold>Commands for Legacy system:")
cecho("\n<white>- <cyan>pp              <ansi_yellow>System Pause")
cecho("\n<white>- <cyan>cp              <ansi_yellow>Health/Mana prio sip change")
cecho("\n<white>- <cyan>Legacy          <ansi_yellow>Legacy general settings")
cecho("\n<white>- <cyan>dsave (name)    <ansi_yellow>Save defense list by name")
cecho("\n<white>- <cyan>defdel (name)   <ansi_yellow>Delete a defense list")
cecho("\n<white>- <cyan>dset (name)     <ansi_yellow>Change to a saved defense set")
cecho("\n<white>- <cyan>defup           <ansi_yellow>Reups saved defences")
cecho("\n<white>- <cyan>defs            <ansi_yellow>Configure clickable def list")
cecho("\n<white>- <cyan>keepup          <ansi_yellow>Configure clickable keepup list")
cecho("\n<white>- <cyan>ndb             <ansi_yellow>Update NDB with current people")
cecho("\n<white>- <cyan>ndbs            <ansi_yellow>NDB current colour settings")
cecho("\n<white>- <cyan>ndbs (city)     <ansi_yellow>NDB City colour settings")
cecho("\n<white>- <cyan>lprompt         <ansi_yellow>Set to use Legacy for custom prompt")
cecho("\n<white>- <cyan>lockpromopt     <ansi_yellow>Toggle configuring the prompt")
cecho("\n<white>- <cyan>en (city)       <ansi_yellow>Enemy everyone in a city")
cecho("\n<white>- <cyan>enteam          <ansi_yellow>Class breakdown for enemy list")
cecho("\n<white>- <cyan>ar (city)       <ansi_yellow>List online army rank 3 and up (You have to honour someone at least once to track their AR)")
 
 
cecho("\n\n<white>- <cyan>feedback \<msg\> <ansi_yellow>Provide feedback to the Legacy team")